name: CICD

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t gastonbordier/sp3-aws-sample .
      - name: Publish image to docker hub
        run : docker push gastonbordier/sp3-aws-sample:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Install docker
        run: sudo snap install docker
      - name: Pull image for docker hub
        run: sudo docker pull gastonbordier/sp3-aws-sample:latest
      - name: Delete old container
        run: sudo docker rm -f sp3-aws-sample-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name sp3-aws-sample-container gastonbordier/sp3-aws-sample
